package com.cgi.sandbox.xml;

import de.odysseus.staxon.json.JsonXMLConfig;
import de.odysseus.staxon.json.JsonXMLConfigBuilder;
import de.odysseus.staxon.json.JsonXMLInputFactory;
import de.odysseus.staxon.json.JsonXMLOutputFactory;
import de.odysseus.staxon.xml.util.PrettyXMLEventWriter;

import javax.xml.stream.*;
import javax.xml.transform.TransformerFactoryConfigurationError;
import java.io.*;

/**
 * Created by galloisg on 08/07/2016.
 */
public class Staxon {

    // see : http://www.programcreek.com/java-api-examples/index.php?api=de.odysseus.staxon.json.JsonXMLConfig

    public static String TEST_XML_STRING =
            "<?xml version=\"1.0\"?>\n" +
                    "<feed xmlns=\"http://www.w3.org/2005/Atom\">\n" +
                    "  <entry id=\"1\">\n" +
                    "    <name>Homer Simpson</name>\n" +
                    "    <birthday>1956-03-01</birthday>\n" +
                    "    <email xmlns=\"http://www.w3.org/2007/app\">chunkylover53@aol.com</email>\n" +
                    "    <phoneNumbers>\n" +
                    "      <home>5551234</home>\n" +
                    "      <mobile>5555678</mobile>\n" +
                    "      <work>5559991</work>\n" +
                    "    </phoneNumbers>\n" +
                    "  </entry>\n" +
                    "  <entry id=\"2\">\n" +
                    "    <name>Marge Simpson</name>\n" +
                    "    <birthday>1965-03-01</birthday>\n" +
                    "    <email xmlns=\"http://www.w3.org/2007/app\">chunkylover53@aol.com</email>\n" +
                    "    <phoneNumbers>\n" +
                    "      <home>152154</home>\n" +
                    "      <work>18644</work>\n" +
                    "    </phoneNumbers>\n" +
                    "  </entry>\n" +
                    "</feed>";

    public static String SIMPE_XML = "<?xml version=\"1.0\"?>\n" +
            "<customer>\n" +
            "    <first-name>Jane</first-name>\n" +
            "    <last-name>Doe</last-name>\n" +
            "    <address>\n" +
            "        <street>123 A Street</street>\n" +
            "    </address>\n" +
            "    <phone-number type=\"work\">555-1111</phone-number>\n" +
            "    <phone-number type=\"cell\">555-2222</phone-number>\n" +
            "</customer>";

    public static String TEST_TIBCO_STRING = "<xml-fragment>\n" +
            "   <proc:basicProcessTemplate xmlns:proc=\"http://www.tibco.com/bx/2009/management/processManagerType\">\n" +
            "      <proc:processQName>\n" +
            "         <proc:moduleName>/ProcessEERPRO/ProcessPackages/ProcessEERPRO.xpdl</proc:moduleName>\n" +
            "         <proc:processName>ProcessEERPROProcess</proc:processName>\n" +
            "         <proc:version>2.0.0.20160627145703568</proc:version>\n" +
            "         <proc:props type=\"displayedName\">ProcessEERPRO</proc:props>\n" +
            "         <proc:props type=\"sortVersion\">2.0</proc:props>\n" +
            "      </proc:processQName>\n" +
            "      <proc:description>*** Generated by TIBCO Business Studio.</proc:description>\n" +
            "   </proc:basicProcessTemplate>\n" +
            "   <proc:basicProcessTemplate xmlns:proc=\"http://www.tibco.com/bx/2009/management/processManagerType\">\n" +
            "      <proc:processQName>\n" +
            "         <proc:moduleName>/ProcessEERPRO/ProcessPackages/ProcessEERPRO.xpdl</proc:moduleName>\n" +
            "         <proc:processName>ProcessEERPROProcess</proc:processName>\n" +
            "         <proc:version>2.0.0.20160630094916359</proc:version>\n" +
            "      </proc:processQName>\n" +
            "      <proc:description>*** Generated by TIBCO Business Studio.</proc:description>\n" +
            "   </proc:basicProcessTemplate>\n" +
            "</xml-fragment>";

    public static String CASE_XML_TEST = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<bdstests:HARMONIE_EERPROElement xmlns:bdstests=\"http://harmonie.socgen.com/bdstests\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"bdstests:HARMONIE_EERPRO\">\n" +
            "   <cid>1816</cid>\n" +
            "   <comptes xsi:type=\"bdstests:EERPRO_ACCOUNT\">\n" +
            "      <numrodecompte>6816ez81r6z1e8</numrodecompte>\n" +
            "      <montantduversement>15050.0</montantduversement>\n" +
            "   </comptes>\n" +
            "   <comptes xsi:type=\"bdstests:EERPRO_ACCOUNT\">\n" +
            "      <numrodecompte>6816ez81r6z1e8</numrodecompte>\n" +
            "      <montantduversement>1500.0</montantduversement>\n" +
            "   </comptes>\n" +
            "</bdstests:HARMONIE_EERPROElement>";

    public static String CASE_CREATE_TEST = "<?xml version=\"1.0\"?>\n" +
            "<CaseRequest>\n" +
            "  <description>string</description>\n" +
            "  <caseBusinessRef>string</caseBusinessRef>\n" +
            "  <state>string</state>\n" +
            "  <status>string</status>\n" +
            "  <initiatorType>string</initiatorType>\n" +
            "  <contextList>\n" +
            "    <name>string1</name>\n" +
            "    <value>string1</value>\n" +
            "  </contextList>\n" +
            "  <contextList>\n" +
            "    <name>string2</name>\n" +
            "    <value>string2</value>\n" +
            "  </contextList>\n" +
            "  <initiatorName>string</initiatorName>\n" +
            "  <acquisitionChannel>string</acquisitionChannel>\n" +
            "  <priority>1</priority>\n" +
            "  <managingAgency>string</managingAgency>\n" +
            "  <managingCu>1</managingCu>\n" +
            "  <isConfidential>true</isConfidential>\n" +
            "</CaseRequest>";

    public static String convertToJson(String xml_data, PrintWriter out) {
        // Conversion based on https://github.com/beckchr/staxon/wiki/Converting-XML-to-JSON
        /*
        * If we want to insert JSON array boundaries for multiple elements, we need to set the <code>autoArray</code>
        * property. If our XML source was decorated with <code>&lt;?xml-multiple?&gt;</code> processing instructions,
        * we'd set the <code>multiplePI</code> property instead.
        */
        JsonXMLConfig config = new JsonXMLConfigBuilder().autoArray(true).prettyPrint(true).namespaceDeclarations(true).build();
        InputStream input = null;
        OutputStream output = null;
        String ret = "error";
        try {
            input = new ByteArrayInputStream(xml_data.getBytes("UTF-8"));
            output = new ByteArrayOutputStream();
            /*
             * Create reader (XML).
             */
            XMLEventReader reader = XMLInputFactory.newInstance().createXMLEventReader(input);

            /*
             * Create writer (JSON).
             */
            XMLEventWriter writer = new JsonXMLOutputFactory(config).createXMLEventWriter(output);

            /*
             * Copy events from reader to writer.
             */
            writer.add(reader);

            /*
             * Close reader/writer.
             */
            reader.close();
            writer.close();
            ret = output.toString();
        } catch (UnsupportedEncodingException ue) {
            out.print("<font color='red'>Unsupported encoding during conversion: XML to JSON.</font>");
        } catch (XMLStreamException se) {
            out.print("<font color='red'>XML Stream exception during conversion: XML to JSON.</font>");
            se.printStackTrace();
        } catch (FactoryConfigurationError fe) {
            out.print("<font color='red'>Factory configuration error during conversion: XML to JSON.</font>");
            fe.printStackTrace();
        } catch (TransformerFactoryConfigurationError tfe) {
            out.print("<font color='red'>Transformer factory configuration error during conversion: XML to JSON.</font>");
            tfe.printStackTrace();
        } finally {
            /*
             * As per StAX specification, XMLEventReader/Writer.close() doesn't close the underlying stream.
             */
            if (output != null)
                try {
                    output.close();
                } catch (IOException e) {
                }
            if (input != null)
                try {
                    input.close();
                } catch (IOException e) {
                }
        }
        return ret;
    }

    public static String convertToXml(String json_data, PrintWriter out) {
        // Conversion based on https://github.com/beckchr/staxon/wiki/Converting-XML-to-JSON
        /*
        * If the <code>multiplePI</code> property is set to <code>true</code>, the StAXON reader will generate
        * <code><xml-multiple></code> processing instructions which would be copied to the XML output. These can
        * be used by StAXON when converting back to JSON to trigger array starts. Set to <code>false</code> if you
        * don't need to go back to JSON.
        */
        JsonXMLConfig config = new JsonXMLConfigBuilder().multiplePI(false).build();
        InputStream input = null;
        OutputStream output = null;
        String ret = "error";
        try {
            input = new ByteArrayInputStream(json_data.getBytes("UTF-8"));
            output = new ByteArrayOutputStream();
           /*
            * Create reader (JSON).
            */
            XMLEventReader reader = new JsonXMLInputFactory(config).createXMLEventReader(input);

           /*
            * Create writer (XML).
            */
            XMLEventWriter writer = XMLOutputFactory.newInstance().createXMLEventWriter(output);
            writer = new PrettyXMLEventWriter(writer); // format output

           /*
            * Copy events from reader to writer.
            */
            writer.add(reader);

           /*
            * Close reader/writer.
            */
            reader.close();
            writer.close();
            ret = output.toString();
        } catch (UnsupportedEncodingException ue) {
            out.print("<font color='red'>Unsupported encoding during conversion: JSON to XML.</font>");
        } catch (XMLStreamException se) {
            out.print("<font color='red'>XML Stream exception during conversion: JSON to XML.</font>");
            se.printStackTrace();
        } catch (FactoryConfigurationError fe) {
            out.print("<font color='red'>Factory configuration error during conversion: JSON to XML.</font>");
            fe.printStackTrace();
        } catch (TransformerFactoryConfigurationError tfe) {
            out.print("<font color='red'>Transformer factory configuration error during conversion: JSON to XML.</font>");
            tfe.printStackTrace();
        } finally {
           /*
            * As per StAX specification, XMLEventReader/Writer.close() doesn't close the underlying stream.
            */
            if (output != null)
                try {
                    output.close();
                } catch (IOException e) {
                }
            if (input != null)
                try {
                    input.close();
                } catch (IOException e) {
                }
        }
        return ret;
    }

    public static void main(String[] args) {
        String json = convertToJson(CASE_CREATE_TEST, new PrintWriter(System.err));
        System.out.println(json);
        String xml = convertToXml(json, new PrintWriter(System.err));
        System.out.println(xml);
    }

}
